- name: Add ff dev edition flatpak remote
  command: flatpak remote-add --if-not-exists --from org.mozilla.FirefoxRepo https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/refs/remotes/org.mozilla.FirefoxRepo
- name: add ffmpeg to plateform
  command: flatpak install flathub org.freedesktop.Platform.ffmpeg
  args:
    creates: /var/lib/flatpak/runtime/org.freedesktop.Platform.ffmpeg
- name: Install firefox developper edition
  command: flatpak install -y org.mozilla.FirefoxRepo org.mozilla.FirefoxDevEdition
  args:
    creates: /var/lib/flatpak/app/org.mozilla.FirefoxDevEdition 
