- name: add nodesource key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: add nodesource repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_lsb.codename }} main
    state: present
    filename: nodejs{{ node_version}}
- name: pin nodejs to nodesource repo
  copy:
    src: files/apt-pref-nodesource
    dest: /etc/apt/preferences.d/nodesource

