---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - import_tasks: tasks/utils.yml
    - import_tasks: tasks/browsers.yml
    - import_tasks: tasks/dev_all.yml
    - name: tune inotify max watchers
      sysctl:
        name: fs.inotify.max_user_watches
        value: 65536
